version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-scraping
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paris_scraping
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - .././database/terrasses.sql:/docker-entrypoint-initdb.d/terrasses.sql
    networks:
      - scraping-net

networks:
  scraping-net:
    driver: bridge
