version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terrasses_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=terrasses_db
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "5000:5000"

volumes:
  mysql_data:
